---
version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  gcp-cli: circleci/gcp-cli@1.8.3

executors:
  deployer:
    docker:
      - image: circleci/php:7.4.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN

jobs:
  build_publish:
    executor: deployer
    working_directory: ~/prestashop
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: Build Package
          command: sh packlink-build.sh ${CIRCLE_TAG}
      - run:
          name: Publish package to production cdn
          command: |
            gsutil cp artifact.zip gs://${PROD_CDN_URL}/modules/prestashop/statics/latest.zip
            gsutil acl ch -u AllUsers:R gs://${PROD_CDN_URL}/modules/prestashop/statics/latest.zip
            gsutil cp artifact.zip gs://${PROD_CDN_URL}/modules/prestashop/statics/${CIRCLE_TAG}.zip
            gsutil acl ch -u AllUsers:R gs://${PROD_CDN_URL}/modules/prestashop/statics/${CIRCLE_TAG}.zip
      - slack/notify:
          color: '#00FF00'
          channel: 'logeecom'
          message: 'A new version has been released: ${CIRCLE_TAG}'
          webhook: '${SLACK_WEBHOOK}'
      - slack/notify:
          color: '#00FF00'
          channel: 'releases'
          message: 'A new version has been released: ${CIRCLE_TAG}'
          webhook: '${SLACK_WEBHOOK}'

workflows:
  version: 2.1
  prestashop_module: 
    jobs:
      - build_publish:
          context:
            - packlink-dockerhub
            - packlink-cdn-publish
            - packlink-github
          filters:
            branches:
            #  ignore: /.*/
              only:
                - fix-circleci
            #tags:
            #  only: /.*/
